server:
  port: 8443
  servlet:
    context-path: "/chatroom/api"
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://abnlch.fun:13306/chat?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123
#  mail:
#    host: smtp.qq.com
#    username:
#    password: fekgfeoytezudigd
#  redis:
#    host: localhost
#    port: 6379

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.example.server.bean
logging:
#  file:
#    #使用相对路径,就会在项目根目录下生成一个info.log文件
#    name: /home/chat.log
  #日志级别 root表示所有包，也可以单独配置具体包 fatal error warn info debug trace off
  level:
    root: info
    com:
      example:
        dao:
          dao: debug
