spring:
  #mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password:
  thymeleaf:
    check-template: false
    check-template-location: false
  data:
    mongodb:
      host: localhost
      database: chat
      port: 27017
  #邮箱配置
  mail:
    host: smtp.qq.com
    username:
    password: fekgfeoytezudigd
  #redis配置
  redis:
    host: localhost
    port: 6379
mybatis:
  mapperLocations: classpath*:mapper/*.xml
  type-aliases-package: com.example.common.bean


server:
  port: 8443
  servlet:
    context-path: "/chatroom"

#打印sql执行语句
logging:
  level:
    com:
      example:
        dao:
          dao: debug
